### ISSUE TITLE
Redmine 500 errors

### ISSUE THREAD

**Issue by tmeekes** [rickbarrette/redmine_qbo#2]
Experiencing a small issue with this plugin

Installation went well, everything seems to be working, but when I go to configure in the plugins menu, I get a Internal error 500. Similarly with the "Customers" tab that is now added.

Looking in the production.log file, found this error repeated twice:

> Started GET "/settings/plugin/redmine_qbo" for 173.239.129.218 at 2016-08-25 19:43:36 +0000
> Processing by SettingsController#plugin as HTML
>   Parameters: {"id"=>"redmine_qbo"}
>   Current user: tmeekes (id=5)
>   Rendered plugins/redmine_qbo/app/views/qbo/_settings.html.erb (138.9ms)
>   Rendered settings/plugin.html.erb within layouts/admin (142.0ms)
> Completed 500 Internal Server Error in 162ms (ActiveRecord: 19.2ms)
> 
> ActionView::Template::Error (undefined method `last_sync' for nil:NilClass):
>     103:     <br/>
>     104:
>     105:     <div>
>     106:         <b>Last Sync: </b> <%= Qbo.last_sync %> <%= link_to " Sync Now", qbo_sync_path %>
>     107: </div>
>   plugins/redmine_qbo/app/models/qbo.rb:56:in`last_sync'
>   plugins/redmine_qbo/app/views/qbo/_settings.html.erb:106:in `_plugins_redmine_qbo_app_views_qbo__settings_html_erb_$
>   app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__1963600310403012080_70049800$
>   app/views/settings/plugin.html.erb:4:in`_app_views_settings_plugin_html_erb__1963600310403012080_70049800053200'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Redmine: v3.3.0.stable
Ruby: v2.1.9-p490
Rails: 4.2.6

Not sure what's causing the issue (newer to using Redmine); this is the first time I've had an issue after a plugin install, and am working to troubleshoot it.

Any thoughts?

Thanks for your work on this.

**Comment by rickbarrette** [comment]
Hello, I'm sorry to get back to you so late. Quick question which commit are you running? I have a bad habit of working in the master branch and I want to see if you are working from a tagged commit, or cloned the master...

Also did you restart your redmine instance after the installation?

Please advise.

**Comment by rickbarrette** [comment]
Looks like the issue you were having was due to calling Qbo.last_sync before the Quickbooks Account was synced.

I have added checks to see if the Quickbooks account is linked before calling this method.
